apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polkadot-claim0
  namespace: {{ .Values.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vol_size }}
