
---
apiVersion: v1
kind: Service
metadata:
  name: private-node
  namespace: {{ .Values.Namespace }}
  labels:
    app: polkadot-node
spec:
  ports:
    - name: "p2p"
      port: {{ .Values.p2p_port }}
      targetPort: {{ .Values.p2p_port }}
    - name: "rpc"
      port: {{ .Values.rpc_port }}
      targetPort: {{ .Values.rpc_port }}
    - name: "ws"
      port: {{ .Values.ws_port }}
      targetPort: {{ .Values.ws_port }}
  selector:
    app: polkadot-node
  clusterIP: None